/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Classes.FileUtils;
import Classes.Pago;
import Classes.Reserva;
import DAO.DAOPago;
import DAO.DAOReserva;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class frmPago extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPago
     */
    public static String idreserva;
    private static int contadorComprobante = 1;

    DAOPago DAO = new DAOPago();
    DAOReserva DaoR = new DAOReserva();

    public frmPago() {
        initComponents();
        if (idreserva != null && !idreserva.isEmpty()) {
            txtidreserva.setText(idreserva);

        }
        Configuracion();
        setFechaEmision();
        asignarNumeroComprobante();
    }

    private void setFechaEmision() {
        Date fechaActual = new Date();
        datFechaEmision.setDate(fechaActual);
        datFechaEmision.setEnabled(false);

        datFechaPago.setDate(fechaActual);
        datFechaPago.setEnabled(false);
    }

    public void Configuracion() {
        txtidpago.setVisible(false);
        txtidreserva.setVisible(false);
        txtcliente.setEnabled(false);
        lblCostoTotal.setEnabled(false);
        lblTotalConsumos.setEnabled(false);
        txtigv.setEnabled(false);
        txtTotalPago.setEnabled(false);
        txtnum_comprobante.setEnabled(false);
        txtruc.setVisible(false);
    }

    private void asignarNumeroComprobante() {
        txtnum_comprobante.setText(String.valueOf(contadorComprobante++));
    }

    private String imprimirPago() {
        StringBuilder contenido = new StringBuilder();
        contenido.append("Cliente: ").append(txtcliente.getText()).append("\n");
        contenido.append("Costo Total: ").append(lblCostoTotal.getText()).append("\n");
        contenido.append("Tipo de Comprobante: ").append(cbotipo_comprobante.getSelectedItem().toString()).append("\n");
        contenido.append("Número de Comprobante: ").append(txtnum_comprobante.getText()).append("\n");
        if (cbotipo_comprobante.getSelectedItem().equals("Factura")) {
            contenido.append("RUC: ").append(txtruc.getText()).append("\n");
        }
        contenido.append("IGV: ").append(txtigv.getText()).append("\n");
        contenido.append("Total Consumos: ").append(lblTotalConsumos.getText()).append("\n");
        contenido.append("Fecha de Emisión: ").append(new SimpleDateFormat("dd/MM/yyyy").format(datFechaEmision.getDate())).append("\n");
        contenido.append("Fecha de Pago: ").append(new SimpleDateFormat("dd/MM/yyyy").format(datFechaPago.getDate())).append("\n");
        contenido.append("Total a Pagar: ").append(txtTotalPago.getText()).append("\n");

        return contenido.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datFechaPago = new com.toedter.calendar.JDateChooser();
        datFechaEmision = new com.toedter.calendar.JDateChooser();
        txtigv = new javax.swing.JTextField();
        txtnum_comprobante = new javax.swing.JTextField();
        cbotipo_comprobante = new javax.swing.JComboBox<>();
        txtidreserva = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtidpago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotalPago = new javax.swing.JTextField();
        lblCostoTotal = new javax.swing.JTextField();
        lblTotalConsumos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        txtruc = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 249, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Pagos"));

        jLabel1.setText("Total Reserva:");

        jLabel2.setText("Cliente:");

        jLabel4.setText("Núm. Comprobante:");

        jLabel5.setText("Tipo Comprobante:");

        jLabel6.setText("IGV:");

        jLabel7.setText("Total Pago:");

        jLabel8.setText("Fecha de Emisión:");

        jLabel9.setText("Fecha de Pago:");

        cbotipo_comprobante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Factura" }));
        cbotipo_comprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipo_comprobanteActionPerformed(evt);
            }
        });
        cbotipo_comprobante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbotipo_comprobanteKeyReleased(evt);
            }
        });

        txtidreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidreservaActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Consumos:");

        jLabel10.setText("RUC:");

        btnPagar.setBackground(new java.awt.Color(244, 245, 244));
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pago.png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.setBorderPainted(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(244, 245, 244));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setBorderPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(new java.awt.Color(244, 245, 244));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/impresora.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setBorderPainted(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(lblCostoTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtigv)
                            .addComponent(cbotipo_comprobante, 0, 137, Short.MAX_VALUE)
                            .addComponent(txtruc)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(lblTotalConsumos)
                            .addComponent(datFechaEmision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotalPago)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(83, 83, 83)
                        .addComponent(txtnum_comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(txtidreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtidpago, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbotipo_comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnum_comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotalConsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnPagar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidreserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidpago, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidreservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidreservaActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            int idReserva = Integer.parseInt(txtidreserva.getText());
            Reserva reserva = DaoR.obtenerReservaPorId(idReserva);

            if (reserva == null) {
                JOptionPane.showMessageDialog(this, "Reserva no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (reserva.getEstadoR().contains("Pagado")) {
                JOptionPane.showMessageDialog(this, "La reserva ya está pagada", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (JOptionPane.showConfirmDialog(rootPane, "¿Se realizó el pago?", "Agregar Pago", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }

            String tipoComprobante = cbotipo_comprobante.getSelectedItem().toString();
            String numComprobante = txtnum_comprobante.getText();
            BigDecimal igv = new BigDecimal(txtigv.getText());
            BigDecimal totalPago = new BigDecimal(txtTotalPago.getText());
            LocalDate fechaEmision = datFechaEmision.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaPago = datFechaPago.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            Date fechaEmisionDate = Date.from(fechaEmision.atStartOfDay(ZoneId.systemDefault()).toInstant());
            Date fechaPagoDate = Date.from(fechaPago.atStartOfDay(ZoneId.systemDefault()).toInstant());

            Pago pago = new Pago(0, idReserva, tipoComprobante, numComprobante, igv, totalPago, fechaEmisionDate, fechaPagoDate);

            DAO.Guardar(pago);

            // Imprimir el pago
            String contenido = imprimirPago();
            String nombreArchivo = "Boleta_" + txtnum_comprobante.getText() + "_" + System.currentTimeMillis() + ".txt";
            FileUtils.escribirPagoEnArchivo(nombreArchivo, contenido);

            // Actualizar estado de la reserva a "Pagado"
            String nuevoEstado;
            if (reserva.getEstadoR().equals("Hospedaje")) {
                nuevoEstado = "Hospedaje-Pagado";
            } else if (reserva.getEstadoR().equals("Reservada")) {
                nuevoEstado = "Reservada-Pagado";
            } else {
                throw new IllegalStateException("Estado desconocido: " + reserva.getEstadoR());
            }

            DaoR.actualizarEstado(idReserva, nuevoEstado);

            JOptionPane.showMessageDialog(this, "Pago registrado e impreso correctamente como " + nombreArchivo);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato de los datos numéricos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato de fecha: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar o imprimir el pago: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cbotipo_comprobanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbotipo_comprobanteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbotipo_comprobanteKeyReleased

    private void cbotipo_comprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipo_comprobanteActionPerformed
        // TODO add your handling code here:
        String tipoComprobante = cbotipo_comprobante.getSelectedItem().toString();
        System.out.println("Tipo de Comprobante seleccionado: " + tipoComprobante); // Mensaje de depuración

        if (tipoComprobante.equals("Factura")) {
            txtruc.setVisible(true);
        } else {
            txtruc.setVisible(false);
        }
    }//GEN-LAST:event_cbotipo_comprobanteActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        try {
        // Obtener el idReserva del campo de texto
        int idReserva = Integer.parseInt(txtidreserva.getText().trim());

        // Obtener la reserva por id
        Reserva reserva = DaoR.obtenerReservaPorId(idReserva);

        if (reserva == null) {
            JOptionPane.showMessageDialog(this, "Reserva no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!reserva.getEstadoR().contains("Pagado")) {
            JOptionPane.showMessageDialog(this, "El estado de la reserva no es 'Pagado'.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Imprimir el pago
        String contenido = imprimirPago();
        String nombreArchivo = "Boleta_" + txtnum_comprobante.getText() + "_" + System.currentTimeMillis() + ".txt";
        FileUtils.escribirPagoEnArchivo(nombreArchivo, contenido);

        JOptionPane.showMessageDialog(this, "Pago impreso correctamente como " + nombreArchivo);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error en el formato de los datos numéricos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al imprimir el pago: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cbotipo_comprobante;
    private com.toedter.calendar.JDateChooser datFechaEmision;
    private com.toedter.calendar.JDateChooser datFechaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField lblCostoTotal;
    public static javax.swing.JTextField lblTotalConsumos;
    public static javax.swing.JTextField txtTotalPago;
    public static javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtidpago;
    public static javax.swing.JTextField txtidreserva;
    public static javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtnum_comprobante;
    private javax.swing.JTextField txtruc;
    // End of variables declaration//GEN-END:variables
}
