/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author Jorge
 */
public class frmVistaHospedaje extends javax.swing.JInternalFrame{

    /**
     * Creates new form frmVistaHospedaje
     */
    public frmVistaHospedaje() {
        initComponents();
        lblCapacidadHabitacion.setText("");
        lblEstadoHabitacion.setText("");
        lblEstadoReserva.setText("");
        lblFechaLlegada.setText("");
        lblFechaSalida.setText("");
        lblIdCliente.setText("");
        lblIdHabitacion.setText("");
        lblIdReserva.setText("");
        lblNombreCliente.setText("");
        lblNumeroHabitacion.setText("");
        lblNumeroNoches.setText("");
        lblPrecioBaseHabitacion.setText("");
        lblTipoHabitacion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        lblTipoHabitacion = new javax.swing.JLabel();
        lblPrecioBaseHabitacion = new javax.swing.JLabel();
        lblFechaLlegada = new javax.swing.JLabel();
        lblNumeroNoches = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        lblEstadoReserva = new javax.swing.JLabel();
        lblNumeroHabitacion = new javax.swing.JLabel();
        lblIdReserva = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        lblCapacidadHabitacion = new javax.swing.JLabel();
        lblIdHabitacion = new javax.swing.JLabel();
        lblEstadoHabitacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de Habitación:");

        jLabel2.setText("Tipo de Habitación:");

        jLabel3.setText("Número de noches:");

        jLabel4.setText("Precio Base:");

        jLabel5.setText("Nombre del Cliente:");

        jLabel6.setText("ID Hospedaje:");

        jLabel7.setText("Fecha de Llegada:");

        jLabel8.setText("Fecha de Salida:");

        jLabel9.setText("Estado:");

        btnCerrar.setBackground(new java.awt.Color(244, 245, 244));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblTipoHabitacion.setText("jLabel1");

        lblPrecioBaseHabitacion.setText("jLabel1");

        lblFechaLlegada.setText("jLabel1");

        lblNumeroNoches.setText("jLabel1");

        lblFechaSalida.setText("jLabel1");

        lblEstadoReserva.setText("jLabel1");

        lblNumeroHabitacion.setText("jLabel1");

        lblIdReserva.setText("jLabel1");

        lblNombreCliente.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroNoches, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEstadoReserva, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaSalida, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaLlegada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecioBaseHabitacion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoHabitacion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumeroHabitacion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdReserva, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdReserva, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroHabitacion)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNombreCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTipoHabitacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblPrecioBaseHabitacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblFechaLlegada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblFechaSalida))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNumeroNoches))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblEstadoReserva))
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addGap(41, 41, 41))
        );

        lblIdCliente.setText("jLabel1");

        lblCapacidadHabitacion.setText("jLabel1");

        lblIdHabitacion.setText("jLabel1");

        lblEstadoHabitacion.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblCapacidadHabitacion)
                .addGap(30, 30, 30)
                .addComponent(lblIdCliente)
                .addGap(18, 18, 18)
                .addComponent(lblIdHabitacion)
                .addGap(18, 18, 18)
                .addComponent(lblEstadoHabitacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCliente)
                    .addComponent(lblCapacidadHabitacion)
                    .addComponent(lblIdHabitacion)
                    .addComponent(lblEstadoHabitacion))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVistaHospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVistaHospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVistaHospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVistaHospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVistaHospedaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblCapacidadHabitacion;
    public static javax.swing.JLabel lblEstadoHabitacion;
    public static javax.swing.JLabel lblEstadoReserva;
    public static javax.swing.JLabel lblFechaLlegada;
    public static javax.swing.JLabel lblFechaSalida;
    public static javax.swing.JLabel lblIdCliente;
    public static javax.swing.JLabel lblIdHabitacion;
    public static javax.swing.JLabel lblIdReserva;
    public static javax.swing.JLabel lblNombreCliente;
    public static javax.swing.JLabel lblNumeroHabitacion;
    public static javax.swing.JLabel lblNumeroNoches;
    public static javax.swing.JLabel lblPrecioBaseHabitacion;
    public static javax.swing.JLabel lblTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
